#!/bin/sh

# Create symbolic links in $HOME

nl='
'
IFS=" $nl"

die() { test -n "$*" && echo "$*" >&2; exit 1; }
warn() { test -z "$NOWARN" && echo "$@" >&2; }

if echo foo | md5sum > /dev/null 2>&1; then
	MD5=md5sum
else
	MD5=md5
fi


base=$(dirname "$0")
test "$(pwd)" = "$HOME" || die "Must run from \$HOME ($HOME)"
cd $HOME

unset force abort
while test $# -gt 0; do
       case $1 in
       -f)  force=1;;
       *)   die unexpected argument: $1;;
       esac
       shift
done

# names is the list to be the target of symlinks
names=$(ls -a "$base" | while read f; do grep -q "^${f}$" $base/blacklist \
	|| echo $f; done)

for file in $names; do
	if test -f "$file" && test "$($MD5 < $HOME/$file)" != \
			"$($MD5 < "$base/$file")"; then
		warn "$file is different, set V=1 to see diff"
		test -n "$V" && diff -u $HOME/$file "$base/$file"
		abort=1
	fi
done

if test -n "$abort" && test -z "$force"; then
       warn "-f to force overwrite"
       exit 1;
fi

test -n "$abort" && warn overwriting

mkdir -p $HOME/.bash-history-dir
mkdir -p $HOME/.config/git
ln -fs ../../$base/.gitignore_global $HOME/.config/git/ignore || die

for file in $names; do
	ln -sf "$base/$file" .${file#.} || die
done

for n in EMAIL UNAME; do
	eval v=\$$n;
	if test -z "$v"; then
		printf "$n not set in environment.  Enter value: "
		eval read $n
	fi
done

if ! test -f $HOME/.gitconfig-user; then
	sed 's/.//' >> $HOME/.gitconfig-user << EOF
	[user]
		email = ${EMAIL?}
		name = ${UNAME?}
EOF
fi

if ! test -f $HOME/.bash-local; then
	cat > $HOME/.bash-local <<- EOF
		EMAIL="$EMAIL"
		NAME="$UNAME"
		export EMAIL UNAME
EOF
fi
