#!/bin/sh

# Run this script from a location to which links should be added.
# (eg, run it from $HOME)

die() { echo "$@" >&2; exit 1; }
warn() { test -z "$NOWARN" && echo "$@" >&2; }
base=$( dirname $(realpath --relative-to=$HOME $0) )
test "$(pwd)" = "$HOME" || warn "Running from $HOME"
test "$1" = main && main=1


cd $HOME

files='
.bash-functions
.bash-interactive-functions
.bash_profile
.bashrc
.ctags
.editrc
.gitconfig
.inputrc
.pystartup
.tmux.conf
.toprc
.vim
.vimrc
'

target() {
	local suffix
	test -n "$main" && test -e $base/$1.primary && suffix=.primary
	echo $base/$1$suffix
}

for file in $files; do
	if test -e $file; then
		if test "$(realpath $HOME/$file)" != \
				"$(realpath $(target $file))"; then
			die "aborting to avoid overwriting $file"
		fi
	fi
done


for file in $files; do test -e $file || ln -sf $(target $file) $file || die; done
