" Load order:
"   1. This file (vimrc), which sources lib/misc.vim early
"   2. syntax/*.vim, triggered by 'syntax on' in this file
"   3. plugin/*.vim (whitespace, statusline, skeleton, foldtext, ...)
"   4. after/plugin/*.vim (indentation, ...)
"   5. Filetype triggers: ftplugin/, after/ftplugin/, after/syntax/

runtime lib/misc.vim

colorscheme wrp
cnoreabbrev e n
noremap v V
noremap V v
noremap ; :
noremap , ;
noremap ' `
noremap ` '
nnoremap <C-G> 1<C-G>
noremap bd! :bd<cr>:bn<cr>
noremap gw :Windo set wrap!<cr>
com! Nt :NERDTree

set noexpandtab
let &tabstop = 8
set shiftwidth=8

packadd! matchit
let b:match_words = '<<<<<<<:=======:>>>>>>>'

let loaded_matchparen=1
set autoindent
set noerrorbells
set exrc    " Enable loading .vimrc from $CWD
set nofileignorecase
set foldopen-=search
set hlsearch
set iskeyword=@,48-57,_,192-255,-
set linebreak  " Do not split words when wrapping
set listchars=extends:%,precedes:%,eol:$,tab:>-,trail:$
set matchpairs+=<:>
set modeline
set modelines=10
set visualbell
set nowrap
set nowrapscan
set scrolloff=0

set t_ti= t_te=  " Disable clear screen on exit
set tildeop
set viminfofile=$HOME/.config/vim/viminfo
set wildmenu
set wildmode=longest,list,full
highlight ColorColumn ctermbg=green
highlight Search ctermfg=red ctermbg=blue
highlight Folded ctermbg=black
syntax on

set includeexpr=substitute(v:fname,'^//','','')

let g:markdown_recommended_style=0
filetype plugin on

highlight Comment ctermfg=darkcyan
highlight DiffChange ctermbg=25
highlight DiffAdd    term=bold ctermbg=5
highlight DiffDelete term=bold ctermfg=12 ctermbg=159
highlight DiffText   term=reverse cterm=bold ctermbg=7
set cinkeys="0{,0},0),!^F,o,O,e"

set formatoptions=cq
set comments=

set swapfile
set directory^=~/.run/vim/swap//
set writebackup
set backupcopy=auto
if has("patch-8.1.0251")
        set backupdir^=~/.run/vim/backup//
end
set undofile
set undodir^=~/.run/vim/undo//

au BufNewFile,BufRead .bash-history setlocal path+=$HOME/.bash-history-dir

autocmd BufEnter,BufReadPost,FileReadPost,BufNewFile,DirChanged *
	\ call system("test -z \"$NORENAMEVIM\" && truncate_left=1 set-title " .
	\ expand("%:t"))

" When editing a file, always jump to the last known cursor position.
autocmd BufReadPost *
	\ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
	\ | exe "normal! g`\""
	\ | endif

" [[: search for a line that ends with { and does not start with whitespace
augroup local_bracket_motion
	autocmd!
	autocmd FileType *
		\ if index(['c', 'cpp', 'go'], &filetype) < 0 |
		\ nnoremap <buffer> <silent> [[ 0?^\S\@=.*{$<CR>$:nohlsearch<CR>|
		\ xnoremap <buffer> <silent> [[ ?^\S\@=.*{$<CR>$:nohlsearch<CR>|
		\ onoremap <buffer> <silent> [[ ?^\S\@=.*{$<CR>$:nohlsearch<CR>|
		\ noremap <buffer> <silent> ]] /^\S\@=.*{$<CR>$:nohlsearch<CR>|
		\ endif
augroup END

autocmd BufEnter * set formatoptions-=ro
autocmd BufEnter * set indentexpr=

if &diff
	highlight DiffAdd ctermbg=5
endif

runtime local/all.vim

" vim: foldenable:sw=4 fdm=indent fdl=1
