#!/bin/sh

# This script is invoked after GIT_EDITOR and takes the name
# of a file containing the proposed commit message as $1.
# It may change the content of the file.
#
# The script runs in the root level of the repository.  In the
# typical case, $1 is relative path beginning ".git/", but if
# .git is a gitdir: regular file, $1 may be a full path.  I don't
# know the full scope of the possibilities, but don't make
# assumptions about the format of $1.

. "$(dirname $0)"/common-hook-functions
backup_name="$1"

main() {
	remove_comments "$@" || die
	if test -n "$SKIP_COMMIT_CHECKS"; then
		test "$SKIP_COMMIT_CHECKS" = silent ||
		warn 'Skipping all commit checks.  (SKIP_COMMIT_CHECKS is set)'
		return 0
	fi
	: ${MAX_GIT_WIDTH:=$(git config commit.max-message-width)}
	: ${MAX_GIT_SUMMARY:=$(git config commit.max-summary-width)}
	check_message "$@" || die "Set SKIP_COMMIT_CHECKS=1 to skip"
	check_words "$1" || die "Set SKIP_COMMIT_CHECKS=1 to skip"
	validate_trailers "$@" || die "Set SKIP_COMMIT_CHECKS=1 to skip"
	check_previous "$@" || die "Set SKIP_COMMIT_CHECKS=1 to skip"
	run_local_hooks "$@" || die "Set SKIP_COMMIT_CHECKS=1 to skip"
}

remove_comments() { perl -i -ne 'print unless m/^\s*#/' "$1"; }

check_previous() {
	if grep -q 'Previously edited commit message:' "$1"; then
		die 'Commit message retains previous messages'
	fi
}


check_words_should_be_skipped() {
	if test -n "$SKIP_SPELLCHECK"; then
		warn 'Skipping spell check (SKIP_SPELLCHECK is set)'
		return 0
	fi

	if test -f "$WORD_FILE" && ! sort -c "$WORD_FILE"; then
		warn "$WORD_FILE is not sorted; not checking words"
		return 0
	fi
	return 1
}

get_words_from_git_log() {
	# only run git log once
	if test -z "$checked_git_log"; then
		checked_git_log=1
		word_list="$word_list
		$(git log --format='%(trailers:separator=%x2C)' | tr -d : | sort -u)
		"
	fi
}

check_word() {
	if test -f "$WORD_FILE"; then
		look -f "$word" "$WORD_FILE" | grep -qi "^$word\$" && return 0
	fi
	readtags "$word" 2> /dev/null | grep -q . && return 0;
	get_words_from_git_log
	printf '%s' "$word_list" | grep -qw "$word" && return 0
	return 1
}

check_words() {
	# Ensure that each word in $1 appears in the dictionary
	: ${WORD_FILE:=/usr/share/dict/words}
	if check_words_should_be_skipped; then return 0; fi
	if ! < "$1" \
		tr -cs '[:alpha:]_' '\n' | sort -u | {
		status=0
		while read word; do
			if ! check_word "$word"; then
				warn "'$word' looks like a spelling error and/or typo"
				status=1
			fi
		done
		test "$status" = 0
	}; then
		if test -z "$BAD_WORDS$BW"; then
			warn "Set BAD_WORDS=1 (or BW) to allow, SKIP_SPELLCHECK=1 to skip"
			return 1
		fi
	fi >&2
}

check_message() {
	bad_end="!?."  # Characters not allowed as final char of summary

	< "$1" >&2 awk '
		/^#/ { next }
		NR==1 && match($0, "fixup!") { exit 0 }
		NR==1 && match($0, "amend!") { exit 0 }
		NR==1 && match($0, "[" end "]$") {
			print "Summary should not end with any of [" end "]"
			status=1
		}
		NR==1 && length > max_summary {
			printf "Summary is %d chars too long" \
				" (max width is ${MAX_GIT_SUMMARY-%d})\n", length - max_summary, max_summary
			status=1
		}
		NR==1 && ! match($0, "^[A-Z]") {
			print "Summary should start with a capital letter"
			status=1
		}
		/[.!?] [^ ]/ {
			printf "2 spaces after a sentence.  line %d: %s\n", NR, $0
			status=1
		}
		/\.  [a-z]/ {
			printf "Sentences must be capitalized.  line %d: %s\n", NR, $0
			status=1
		}
		NR > 1 && length > max_width {
			printf "Line %d (%s...) is %d chars too long (max width is ${MAX_GIT_WIDTH-%d})\n", \
				NR - 2, substr($0, 1, 10), length - max_width, max_width
			status=1
		}
		END {exit status}

	' max_width=${MAX_GIT_WIDTH:-72} max_summary=${MAX_GIT_SUMMARY:-50} end="${bad_end}"
}

# Ensure that all required trailers are present
validate_trailers() {
	if test -z "$(git config commit.required-trailer)"; then
		return
	fi
	local fail
	local present_trailers=$(git interpret-trailers --parse "$1")
	for value in $(git config commit.required-trailer | tr , ' '); do
		if ! echo "$present_trailers" |
			awk '$1 == "'"$value"'" {print $2}' FS=': ' |
			grep -q .
		then
			fail=${fail:+$fail, }$value
		fi
	done
	if test -n "$fail"; then
		die "Missing required trailers: $fail" \
			"You can add trailers to \$t, a comma separated list of k:v pairs" \
			"Disable check with: git config commit.required-trailer ''" \
			;
	fi
}

main "$@"
