#!/bin/sh

. "$(dirname $0)"/common-hook-functions

while read local_ref local_obj remote_ref remote_obj; do
	test "$local_ref" = '(delete)' && continue
	if ! echo "${remote_ref#refs/heads/}" | grep -qE "${BRANCH_ERE_MATCH:-.}"; then
		die "Bad remote branch name: $remote_ref" \
			"Branch names must match BRANCH_ERE_MATCH:'$BRANCH_ERE_MATCH'"
	fi

	if test -z "$ALLOW_WIP" &&
		git show --pretty=format:%s --no-patch "$local_ref" |
			grep -w WIP
	then
		die "$local_ref contains 'WIP'"
	fi

	if \
		git show --pretty=format:%B --no-patch "$local_ref" |
			grep -q 'Previously edited commit message:'
	then
		die "$local_ref contains log message with previously edited commit"
	fi

	git rev-list ${remote_obj}..${local_obj} | while read oid; do
		if git show -s --format=%B "$oid" \
			| git interpret-trailers --only-trailers \
			| grep -q '^Type: WIP'
		then
			short=$(echo "$oid" | cut -b 1-9)
			die "$short is work in progress"
		fi
	done
done >&2
