#!/bin/sh

# This script is invoked before GIT_EDITOR and takes the name
# of a file containing the proposed commit message as $1.  See
# githooks(5) for 2nd and 3rd argument.

# Parse t and trailer from the environment to apply trailers
# to the commit message.

. "$(dirname $0)"/common-hook-functions
main() {
	check_t_for_trailers "$@" || return 1
	run_local_hooks "$@"

	# Only append saved message for normal commits
	if want_to_append_previous "$@"; then
		append_saved_message "$1".bak >> "$1"
	fi
}

want_to_append_previous() {
	# Append saved message except during merge, squash, rebase, or amend
	case "$2" in
	merge|squash|rebase|amend) return 1;;
	esac

	# Do not append if we're in the middle of a rebase (interactive or not)
	if
		test -d "$(git rev-parse --git-dir)/rebase-merge" ||
		test -d "$(git rev-parse --git-dir)/rebase-apply"
	then
		return 1
	fi

	# Do not append if GIT_REFLOG_ACTION indicates we're rebasing
	case "${GIT_REFLOG_ACTION-}" in
	*rebase*) return 1;;
	esac

	return 0
}


# The environment variable t (or "trailer") can be a comma-separated list of
# trailer-value pairs in the form name:value.  Insert them as
# trailers into the commit message
check_t_for_trailers() {
	test -z "${t-$trailer}" && return
	printf '%s\n' "${t-$trailer}" | tr , \\n |
	while IFS=: read k v; do
		if test -z "$v"; then v=$k; k=Type; fi
		git-interpret-trailers --in-place --if-exists addIfDifferent \
			--trailer "$k=$v" "$1" || return 1
	done
}

append_saved_message() {
	if ! test -f "${1}"; then return; fi
	cat <<- EOF

	# Previously edited commit message:
	EOF
	sed -e 's/^/# /' "${1}"
}

main "$@"
