#!/bin/sh

# Insert words into $WORD_FILE

# TODO Make a local option.  There should be some mechanism
# by which words are defined per git repository.

word_path=${WORD_FILE:-/usr/share/dict/words}

trap 'rm -f "$tmp" "$tmp2"' 0

# Grrr mktemp seems broken on this box. Stupid Apple
mkdir -p "/tmp/$USER" || exit
mktemp() { echo "/tmp/${USER}/$1"; }
tmp=$(mktemp insert_word1.$$)
tmp2=$(mktemp insert_word2.$$)

for x; do
	printf '%s\n' "$x" | tr '[:upper:]' '[:lower:]'
done > "$tmp" || exit
cat "$word_path" >> "$tmp" || exit

sort -u "$tmp" > "$tmp2" || exit

size() { stat -f %z "$1"; }

if test "$(size "$tmp2")" -gt "$(size "$word_path")"; then
	cat "$tmp2" > "$word_path"
else
	echo "New file is not bigger.  No words added." >&2
	exit 1
fi



if git -C "${WORD_FILE%/*}" rev-parse HEAD > /dev/null; then
	git -C "${WORD_FILE%/*}" add "${WORD_FILE##*/}"
	subject="Add words $(echo "$*" | sed -E -e 's/  */, /g' -e 's/(.{40}).*/\1/')"
	git -C "${WORD_FILE%/*}" commit -m "$subject"
fi
