#!/bin/sh

cd $HOME/.bash-history-dir || exit
mkdir -p .old || exit

for f in shell-pid*; do
	pid=${f#shell-pid-}
	kill -0 $pid 2> /dev/null && continue  # Skip still running shells
	cat $f >> .old/$f
	rm ${V:+-v} $f | tr \\140 "'"
done
