#!/bin/sh

if test "$V" -gt 3 2> /dev/null; then set -x; fi

cd $HOME/.bash-history-dir || exit
mkdir -p .old || exit

test -n "$V" && echo "Archiving history for shells:"

for pid in *; do
	if ! test "$pid" -gt 0 2> /dev/null; then
		echo "$pid" is not valid as a pid >&2
		continue
	fi
	kill -0 "$pid" 2> /dev/null && continue  # Skip still running shells
	cat "$pid" >> ".old/$pid" \
	&& rm ${V:+-v} "$pid" | tr \\140 "'"
done
