#!/bin/sh

test -n "$V" && set -x

cd $HOME/.bash-history-dir || exit
mkdir -p .old || exit

for f in .bash-history-*; do
	pid=${f#.bash-history-}
	if ! test "$pid" -gt 0 2> /dev/null; then
		echo "$pid" is not valid as a pid >&2
		continue
	fi
	kill -0 $pid 2> /dev/null && continue  # Skip still running shells
	cat $f >> .old/$f \
	&& rm ${V:+-v} $f | tr \\140 "'"
done
