#!/bin/sh

test -n "$V" && set -x

cd $HOME/.bash-history-dir || exit
mkdir -p .old || exit

for f in *; do
	if ! test "$f" -gt 0 2> /dev/null; then
		echo "$f" is not valid as a pid >&2
		continue
	fi
	kill -0 $f 2> /dev/null && continue  # Skip still running shells
	cat $f >> .old/$f \
	&& rm ${V:+-v} $f | tr \\140 "'"
done
