#!/bin/sh

if test "$RECURSION_GUARD" = $$; then
	echo "$0 is recursing; aborting" >&2
	exit 1
fi

if test -z "$SHELL" || test "${SHELL##*/}" = "${0##*/}";
	then SHELL=/bin/bash
fi

if test $# = 2 && test "$1" = -c; then
	s=$2
else
	s=$(printf "$SHELL"; printf ' %q' "$@")
fi

printf "[$(date -Iseconds)] $s\n" >> $HOME/.command-history.log

RECURSION_GUARD=$$ exec "$SHELL" "$@"
