#!/bin/sh

# Simple wrapper that logs commands to a file
# This does not log the output of the command, but the command
# itself.  This is basically producing a history file.
bash_wrapper_output=${bash_wrapper_output-$HOME/.command-history.log}

if test "$RECURSION_GUARD" = $$; then
	echo "$0 is recursing; aborting" >&2
	exit 1
fi

if test -z "$SHELL" || test "${SHELL##*/}" = "${0##*/}";
	then SHELL=/bin/bash
fi

if test $# = 2 && test "$1" = -c; then
	s=$2
else
	s=$(printf "$SHELL"; printf ' %q' "$@")
fi

printf "# $(date +%s)\n$s\n" >> $bash_wrapper_output

RECURSION_GUARD=$$ exec "$SHELL" "$@"
