#!/bin/sh

# Template for `git-bug bug comment edit COMMENT_ID`.
# Prints the current (compiled) text of the commented-on bug comment so the
# user can edit it. Relies on `git-bug bug comment` which reuses git-bug's
# snapshot compile (Lamport-clock-ordered), so it always returns the winning
# version of the text rather than raw op blobs from git.

# $1=edit|new  $2=comment id  $3=bug id  $4=bug title  $5=current value of comment

case $1 in
new)  m="Adding a comment to";;
edit) m="Editing comment $2 in";;
esac

if test "$1" = edit; then
	echo
	echo "$5"
fi

echo "# $m bug $3"
