#!/bin/sh

# Filter $1 (or ~/.bash-history) and purge all simple commands
< ${1-$HOME/.bash-history} \
perl -wnE 'no warnings "experimental::smartmatch";
	# Commands which will be removed
	my @skip = qw (
		airflow
		cal
		cat
		cd
		date
		echo
		env
		exec bash
		git
		gitk
		grep
		head
		history
		kill
		less
		ls
		man
		mkdir
		more
		mv
		pip
		pwd
		rm
		ssh
		tail
		tmux
		touch
		type
		unset
		unzip
		vi
		vim
		virtualenv
		which
	);
	if( /^#[0-9]{10}/ ){
		$ts = $_;
		$state = "cmd";
		next;
	}

	# Ignore simple commands
	if( $state eq "cmd" ) {
		if( /^[a-z]( |\n)/ ) {
			$state = "skip"
		} elsif( /^[a-z]{2}$/ ) {
			$state = "skip"
		} else {
			($cmd, ) = split " ";
			if ($cmd ~~ @skip) {
				$state = "skip";
			}
		}
	}
	next if( $state eq "skip");
	print $ts if $state eq "cmd";
	$state = "keep" if $state eq "cmd";
	print if $state eq "keep";
	'
