#!/bin/sh

< $HOME/.bash-history \
perl -wne '
	if( /^#[0-9]{10}/ ){
		$ts = $_;
		$state = "cmd";
		next;
	}

	# Ignore simple commands
	if( $state eq "cmd" ) {
		$state = "skip" if /^[a-z]( |\n)/;
		$state = "skip" if /^[a-z]{2}$/;   # 2 letter cmds w/no args
		foreach $cmd ( qw(
			airflow
			cal
			cat
			cd
			cd
			date
			echo
			env
			exec bash
			git
			gitk
			grep
			head
			history
			kill
			less
			ls
			man
			mkdir
			more
			mv
			pip
			pwd
			rm
			ssh
			tail
			tmux
			touch
			type
			unset
			unzip
			vi
			vim
			virtualenv
			which
			)
		){
			$state = "skip" if /^$cmd( |$)/;
		}
	}
	next if( $state eq "skip");
	print $ts if $state eq "cmd";
	$state = "keep" if $state eq "cmd";
	print if $state eq "keep";
	'
