#!/bin/sh

# Execute a command, prepending headers to stdout and stderr
add_header() {
	perl -mPOSIX -pe "s/^/$1: /;
		print POSIX::strftime '%y/%m/%d %H:%M:%S: ', gmtime"
}


{ { $@ | add_header stdout >&3; } 2>&1 | add_header stderr; } 3>&1
