#!/bin/sh

# Filter the stream, prepending timestamp and arguments to each line
add_header() {
	perl -mPOSIX -pe "\$m='$*'; s/^/\$m: /;
		print POSIX::strftime '%y/%m/%d %H:%M:%S: ', gmtime"
}

# Execute the command, adding timestamp and labels to output streams
{ { $@ | add_header stdout >&3; } 2>&1 | add_header stderr; } 3>&1
