#!/bin/sh

# Execute commands, prepending timestamps with terminal color sequences to output.

get_time='printf "%s: %s", scalar(localtime), $_'
exec 3>&1
{ "$@" 2>&4 |
	perl -MTerm::ANSIColor -nwe "print color('reset'); $get_time" >&3; } 4>&1 |
	perl -MTerm::ANSIColor -nwe "print color('red');   $get_time" >&2
