#!/bin/sh

logfile=$HOME/tmp/druva-killer-log
trap 'rm -f $logfile' 0
exec > $logfile 2>&1

echo $$

log() { printf "%s: %s\n" "$(date)" "$*"; }

killemall() {
	for pid;
	do
		test "$pid" -gt 0 || continue
		ps -o command= $pid | grep -q '[D]ruva.*inSync' || continue
		log terminating $pid
		sudo kill $pid
	done
	sleep 2
	for pid;
	do
		ps -o command= $pid | grep -q '[D]ruva.*inSync' || continue
		log killing $pid
		sudo kill -9 $pid
	done
}

unset pidlist
while test -n "$pidlist" || sleep 15; do
	pidlist=$(ps ax | awk '/[D]ruva.*inSync/{print $1}')
	killemall $pidlist
done
