#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Std;

my %args;
getopts('tla', \%args);
# Use -t or -l to display local time.  -a to display local and UTC

my $now = time();
my $tz = (localtime($now))[2] - (gmtime($now))[2];

sub handle_line($) {
	$_ = shift(@_);
	if ($args{t} || $args{l} || $args{a}) {
		s/([0-9]{9,10})/sprintf "%s (%sT%d)", $1, scalar localtime $1, $tz/ge;
		if( $args{a}) {
			s/([0-9]{9,10})/sprintf "%s (%sUTC)", $1, scalar gmtime $1/ge;
		}
	} else {
		s/([0-9]{9,10})/sprintf "%s (%sUTC)", $1, scalar gmtime $1/ge;
	}
	print;
}

foreach my $arg (@ARGV) {
	if(open(my $fh, $arg)) {
		while( <$fh> ) {
			handle_line($_)
		}
	} else {
		handle_line($arg . "\n")
	}
}
