#!/bin/sh

func=gmtime
desc=GMT
test "$1" = -l && {
	func=localtime
	desc=local
	shift
}

if test -n "$*"; then
	for x; do echo "$x"; done
else
	cat;
fi \
| perl -pe 's/([0-9]{9,10})/sprintf "%s (%s '$desc')", $1, scalar '$func' $1/ge'

#| perl -pe 'ntf "%10s: %s\n", $_, scalar localtime $_'
