#!/bin/sh

# Attach/switch to the pane running the pid given as $1.
# If no argument is given and stdin is not a tty, read anything that looks like
# a pid and present it to the user via select

die() { echo "$@" >&2; exit 1; }
nl='
'

if test $# = 0 && test -t 0; then scrape | exec "$0" "$@"; fi

if test $# = 0 && test -t 1 && ! test -t 0; then
	# reading from a pipe, outputting to tty, no argument given.  Try
	# to scrape pids from stdin.
	trap 'rm -f $TMP' 0
	TMP=$(mktemp)
	IFS="$nl"
	ps -o pid=,comm= $(grep -i process | grep -woE '[0-9]+' |
		grep -v ^$PPID\$ | # Skip the shell used to invoke this script
		sort -u) > $TMP

	test -s $TMP || die "${ERRMSG-No processes from which to select}"

	if test "$(wc -l < $TMP)" -eq 1; then
		response=1
	else
		PS3="${PROMPT-Select process to jump to}: "
		nl < $TMP
		test -z "$response" && read -p "$PS3" -t 5 response < /dev/tty
	fi
	if test -n "$response"; then
		pid=$( awk "NR == ${response}{print \$1}"  $TMP )
		set -- $pid
	else
		die timeout
	fi
fi

ppid=$(ps -o ppid= ${1?No pid specified})
target_window=$(tmux list-panes -a -F "#{session_name}:#{window_index}.#{pane_index} #{pane_pid}" |
	awk '$2 == ppid{ print $1 }' ppid="$ppid")

if test -n "$TMUX_PANE"; then # We are running in tmux
	prompt="Hit enter to move to $target_window."
	prompt="$prompt  Use <prefix>p or 'tmux select-window -t $TMUX_PANE' to return here."
	read -p "$prompt" < /dev/tty
	tmux display-message -p '#{session_name}:#{window_index}' >> ~/.config/wrp/tmux_prev_window
	tmux switch-client -t $target_window
	tmux select-window -t $target_window
else
	tmux attach-session -t $target_window
fi
