#!/bin/sh -x

# Get the value of the environment variable $1 in a list of pids

echo >&2 "This script is broken on macos, as it is no longer possible to
get environment envariables from another process."
exit 1

var=${1?No variable given}
shift
if test -d /proc; then
	for pid; do
		printf "%s " "$pid"
		tr \\0 \\n < /proc/${pid}/environ |
			awk -F= "/$var/{printf \"%s \", \$2}"
		printf "%s\n" "$(ps -o cmd= $pid)"
	done
else
	for pid; do
		ps eww "$pid" | tr ' ' \\n | awk "\$1 == \"$var\"{print \$2}" FS==
	done
fi | grep .
