#!/bin/sh

# Read a list of paths from stdin.  Output one of the most
# frequently seen directory.
# Relies on no paths having embedded newlines in the name.

awk '{ $NF="" }
	++a[$0] > max {
		max=a[$0];
		res=$0
	}	
	END {print res}
' FS=/ OFS=/
	
