#!/bin/sh

# Archive branches by creating a ref in refs/archive
# and deleting the branch.  If no arguments are given,
# archive the current branch after detaching

if test $# = 0; then
	set -- $(git rev-parse --abbrev-ref HEAD)
	# base=$(git base-branch) || exit
	# git symbolic-ref HEAD refs/heads/$base
	git checkout --detach
fi

for branch; do
	git update-ref refs/archive/"${branch}" "${branch}" '' \
	&& git branch -D "${branch}"
done

