#!/bin/sh

top=$(git rev-parse --show-toplevel)
remote="$(command git rev-parse --symbolic-full-name @{upstream} 2> /dev/null)"
branch="$(git rev-parse --abbrev-ref HEAD)"
cat <<- EOF
	top:      $top
	cwd:      $(pwd)
	branch:   ${branch}
	upstream: ${remote:-none}
EOF
