#!/bin/sh

# Archive branches by creating a ref in refs/archive
# and deleting the branch.  If no arguments are given,
# archive the current branch after detaching

current_branch=$(git rev-parse --abbrev-ref HEAD)
if test $# = 0; then
	set -- "$current_branch"
fi

for branch; do
	if test "$branch" = "$current_branch"; then
		echo "Detaching and archiving the current branch: $branch"
		git checkout --detach
	fi
	git update-ref refs/archive/"${branch}" "${branch}" '' \
	&& git branch -D "${branch}"
done

