#!/bin/sh

url=$1
shift

case $url in
http*)
	# By default, remap name to use ssh
	if test -z "$HTTP_OK"; then
		echo 'Remapping http target to git@ to use ssh.  To force http, set HTTP_OK' >&2
		url=$(printf '%s\n' "$url" | sed -e 's|.*://|git@|' -e 's@/@:@')
		shift
	fi
;;
esac


# Parse the url to specify a name for origin
case $url in
*github*) origin=github;;
esac

set -- clone --depth 3 --no-single-branch ${origin:+--origin="$origin"} "$url" "$@";
printf 'git %s\n' "$*" >&2
git "$@" && echo 'cloned to a depth of 3; to make full, run git fetch --unshallow'
