#!/bin/sh

# Print log in brief format (one line per commit)
#
# You may set t to a comma separated list of trailers to be displayed
# in the log output, and set w to a comma separated list of integer
# values giving the width of the fields in which the trailer is
# displayed.  The final value is w is used for all subsequent fields
# if the lengths of t and w do not match.  The idea here is
# that you can specify trailers with 'git config --add log.default-trailer'
# or override with t at the command line.   For example, to
# always show the "language" and "type" trailers, use:
#
# w=8,4 t=language,type g l1
#
# Any trailer keys listed in commit.required-trailer are also
# listed if t is unspecified.
#
# Configs:
#  log.oid-width           number of characters used for oid
#  log.author-width        number of characters used for author
#  log.trailer-width (1)   comma-separated list of display width of trailers
#  log.default-trailer     comma-separated list of trailers to display
#  commit.required-trailer comma-separated list of trailers to display
#
#  Note: (1) If trailer-width is shorter than default-trailer, the last
#            value will be used.  If longer, excess values are ignored.
#
# Environment:
#    NO_HEADERS               if unset, prepend a header line
#    GITLOG_AUTHOR_WIDTH      override log.author-width

# TODO: after clone, configure log.trailer-width and maybe others

usage() { sed -E -e 1,2d -e '/^$/q' -e 's/#.?//' "$0";}
die() { echo "$*" >&2; exit 1; }

initialize() {
	cd ${GIT_PREFIX:-.} || exit

	local _cfg_author_width _cfg_trailer_width

	# Terminal capabilities for highlighting refs (only when output is a tty)
	if test -t 1; then
		use_color
	else
		truncate="%<($(($(tput cols) / 3)),trunc)"
	fi

	# *_width is the number of characters used in the display
	oid_width=$(git config log.oid-width || echo 8)

	trailers=${t-"$( {
		git config log.default-trailer
		git config commit.required-trailer
		} | tr , \\n | sort -u | sed -e '/^ *$/d' | tr \\n , | sed -e 's/,$//')"}

	_cfg_trailer_width="$(git config log.trailer-width)"
	trailer_width=${w-${_cfg_trailer_width:-11}}
	check_csl "$trailer_width" || die "log.trailer-width: $trailer_width"
	trailer_fmt=$(build_trailer_fmt)

	_cfg_author_width="$(git config log.author-width)"
	author_width=${GITLOG_AUTHOR_WIDTH:-${_cfg_author_width:-20}}

	# Current versions of less with --header do not behave well with
	# -F, and I get a screen full of ~ when the input is short.  As
	# a workaround, just omit --headers if -n is specified.
	for x; do
		case $x in
		-h) usage; exit 0;;
		--date=format:%FT%T%z) date_width=24;;
		--date=iso) date_width=25;;
		--date=rfc) date_width=38; tab=%x09;;
		--graph) NO_HEADERS=1;;
		esac
	done
}

check_csl() {
	# check that each argument is a comma separated list of
	# positive integers
	local x
	for x; do
		printf '%s\n' "$x" | tr , \\n | while read val; do
			if ! test "$val" -ge 0 2> /dev/null; then
				die "'$x' is not an integer"
			fi
		done || return 1
	done
	return 0
}

use_color() {
	green="%C(green)"
	yellow="%C(yellow)"
	red="%C(red)"
	blue="%C(blue)"
	reset="%C(reset)"
	rev_on=$(tput setab 3)
	rev_off=$(tput op)
	color_flag="--color=always"
}

# TODO: clean up this function; it is mostly obsolete
check_pager() {
	if test -z "$NO_HEADERS"; then
		header=$(
			printf "%-$((oid_width+1))s" oid
			if test "${date_width:-0}" -gt 11; then
				printf "%-$((date_width+1))s" 'author date'
			fi
			printf "%-$((author_width+1))s" $(if test "$author_width" -lt 6; then
				printf '%%an'; else printf author; fi)
			echo "$trailers" | tr , '\n' \
			| while read t; do
				test -z "$t" && continue
				width=${trailer_width%%,*}
				if test "$width" -gt 0; then
					width=$((${width} + 2))
					printf "%-${width}s" "$t" | cut -b 1-$width | tr -d \\n
					printf ' '
				fi
				trailer_width=${trailer_width#*,}
			done
			printf summary
		)
	fi
}

build_ref_pattern() {
	# Build sed pattern to highlight specified refs in reverse video
	# Default to current branch if no refs specified
	local has_refs=""
	for arg; do
		case "$arg" in
		-*) ;;
		*) has_refs=1; break;;
		esac
	done
	if test -z "$has_refs"; then
		set -- "$@" "$(git symbolic-ref --short HEAD 2>/dev/null)"
	fi
	local pattern=""
	for arg; do
		case "$arg" in
		-*|"") ;;
		*) pattern="${pattern}s@(^|[^a-zA-Z0-9_/-])${arg}([^a-zA-Z0-9_/-]|\$)@\\1${rev_on}${arg}${rev_off}\\2@g;";;
		esac
	done
	printf '%s\n' "${pattern}n"
}

main() {
	initialize "$@"
	check_pager
	ref_pattern=$(build_ref_pattern "$@")
	{
	test -z "$NO_HEADERS" && printf '%s\n' "$header"
	git --no-pager log \
		--date=format:"" \
		${tab+--expand-tabs} \
		${color_flag} \
		--abbrev=${oid_width} \
		--format=tformat:"$(printf '%s' "$(:
			)${green}%h$(:
			)${yellow}% ad${tab}$(:
			)${red}%<(${author_width},trunc)% an$(:
			)${reset}${trailer_fmt}$(:
			)${truncate}% s$( :
			)${blue}% D$(:
			)${reset}" | sed -E 's/  +//g' )" "$@"
	} |
	sed -E -e "$ref_pattern" -e "$ref_pattern" |
	if test -t 1; then
		$(git var GIT_PAGER)
	else
		cat
	fi
}

build_trailer_fmt() {
	awk -v fmt=" [%%<(%s,ltrunc)%%(trailers:key=%s,separator=%%x2C,valueonly)]" '
		BEGIN {
			split(ARGV[1], f, ",");
			n=split(ARGV[2], g, ",");
			for (i=1; i <= length(f); i++) {
				width = i < n ? g[i] : g[n]
				if (width) {
					printf(fmt, width, f[i])
				}
			}
		}
	' "${trailers}" "${trailer_width}"
}

main "$@"
