#!/bin/sh

depth=
url=$1
shift

if test "$url" -gt 0 2> /dev/null; then
	depth=$url
	url=$1
	shift
fi

case $url in
http*)
	# By default, remap name to use ssh
	if test -z "$HTTP_OK"; then
		echo 'Remapping http target to git@ to use ssh.  To force http, set HTTP_OK' >&2
		url=$(printf '%s\n' "$url" | sed -e 's|.*://|git@|' -e 's@/@:@')
		shift
	fi
;;
esac


# Parse the url to specify a name for origin
case $url in
*github*) origin=github;;
esac

set -- clone ${depth:+--depth $depth} --no-single-branch ${origin:+--origin="$origin"} "$url" "$@";
printf 'git %s\n' "$*" >&2
git "$@" || exit

if test -n "$depth"; then
	echo "cloned to a depth of $depth.  To make full, run:"
	echo 'git fetch --unshallow'
fi
