#!/bin/sh

# Find commits in the main branch (or the branch given in b) which
# contain the given blobs
branch=${b-$(git-base-branch)}


process_blob() {
	git log --format="%at %h ${1:0:8} %s" --find-object="$1" $branch
}

for x; do
	if test -f "$x"; then
		awk '/^index/{print substr($1,7,8)}' FS=. "$x"
	else
		echo "$x"
	fi
done | sort -u |
while read b; do
	process_blob "$b"
done | sort -n
