#!/bin/sh

top=$(git rev-parse --show-toplevel)
if remote="$(command git rev-parse --symbolic-full-name @{upstream} 2> /dev/null)"
then
	remote_oid=" ($(git rev-parse --short "$remote"))"
fi
branch="$(git rev-parse --abbrev-ref HEAD)"
summary=$(git for-each-ref --format="(%(objectname:short)) %(push:track)" refs/heads/"$branch")

sed -e 's/ *$//' <<- EOF
	branch:   ${branch} $summary
	upstream: ${remote:-none}$remote_oid
	top:      $top
	cwd:      $(pwd)
	describe: $(git describe --dirty 2>&1)
EOF
