#!/bin/sh

cmd='fetch --all --no-tags'

test -n "$1" || set -- .

for top; do
	(
	cd $top
	pwd >&2
	for dir in *; do
		test -d "$dir" \
		&& if echo "$dir" | tr -dc ' \n\t/' | grep -q . ; then
			echo "Stubbornly refusing to work with name '$dir'" >&2
			continue
		fi
		label=$(basename $(pwd)):$dir
		(
		cd "$dir" \
		&& {
			git ${cmd} 2>&1 1>&3 | sed "s/^/[$label] /" >&2
		} 3>&1 | sed "s/^/[$label] /"
		)
	done
	)
done
