#!/bin/sh

top=$(git rev-parse --show-toplevel) || exit
if remote="$(command git rev-parse --symbolic-full-name @{upstream} 2> /dev/null)"
then
	remote_oid=" ($(git rev-parse --short "$remote"))"
fi
branch="$(git rev-parse --abbrev-ref HEAD)"
summary=$(git for-each-ref --format="(%(objectname:short)) %(push:track)" refs/heads/"$branch")
version=$(git describe --tags --dirty 2> /dev/null)

sed -e 's/ *$//' <<- EOF
	branch:   ${branch} $summary
	upstream: ${remote:-none}$remote_oid
	top:      $top
	cwd:      $(pwd)
	version:  ${description:-unversioned}
EOF


git status --short

gitdir=$(git rev-parse --git-dir 2>/dev/null) || exit 1
if test -d "${gitdir}/rebase-apply" || test -d "${gitdir}/rebase-merge"; then
	echo "rebase or am in progress"
elif test -f "${gitdir}/MERGE_HEAD"; then
	echo "merge in progress"
elif test -f "${gitdir}/CHERRY_PICK_HEAD"; then
	echo "cherry-pick in progress"
elif test -f "${gitdir}/REVERT_HEAD"; then
	echo "revert in progress"
elif test -d "${gitdir}/sequencer"; then
	echo "sequencer operation in progress (revert/cherry-pick)"
fi
