#!/bin/sh

if test "$1" = -h; then
	echo 'run git recursively and prepend path to output'
	exit 0
fi

delim=': '
if test "$1" = grep; then
	# We want to make sure the prefix of each line
	# is a valid path so we can pipe directly to vi
	delim='/';
	if test -t 1; then
		shift
		set -- grep --color=always "$@"
	fi
fi

header() { sed -e "s@^@${dir}${delim}@" -e 's@\./@@'; }

# TODO (?) probably not worth the effort, but assuming that a directory is
# the top-level of a repo merely because of the existence of .git is fragile.
# This will almost certainly not behave well with submodules (which is a
# tautology, as submodules are a scourge) and will completely miss many
# edge cases.  But this script does not need to be particularly robust.
find . -type d -name .git | while read git_dir; do
	dir="${git_dir%/.git}"
	{ { git -C "$dir" "$@" 2>&3 | header >&4; } 3>&1 | header >&2; } 4>&1 &
	if ! wait $!; then RV=1; fi


done | ${PAGER-more}

exit ${RV-0}
