#!/bin/sh

cd "${1?}"
for dir in *; do (
	test -d "$dir" \
	&& if echo "$dir" | tr -dc ' \n\t/' | grep -q . ; then
		echo "Stubbornly refusing to work with name '$dir'" >&2
		continue
	fi

	cd "$dir" \
	&& {
		git fetch 2>&1 1>&3 | sed "s/^/[ERROR-$dir] /" >&2
	} 3>&1 | sed "s/^/[$dir] /"
); done 2>&1
