#!/bin/sh

# Create a new commit which squashes HEAD into $1.
# Define "edit_msg" in the environment if you want to edit the commit message.

die() { printf 'FATAL: %s\n' "$*" >&2; exit 1; }
usage() { sed -nE -e 1,2d -e '/^$/q' -e 's/#.?//p' "$0";}
cleanup() {
	echo >&2 Aborting and resetting to "$current"
	git reset --hard "$current"
}
generate_log_msg() {
	local format='# ---- %h -- %ai%n%B%n%N'
	printf 'Squash commits from %s to %s\n\n' "$current" "$base"
	git log -n 1 --format="$format" "$1" || return 1
	git log --reverse --format="$format" "$1".. || return 1
}
test "$1" = -h && usage && exit 0

if ! git rev-parse --verify HEAD >/dev/null 2>&1; then
	die There is no current HEAD
fi

if ! git diff-index --quiet HEAD; then
	die Repo is dirty
fi

current=$(git rev-parse --short HEAD) || exit
base=$(git rev-parse --short "$1") || exit
msg=$(generate_log_msg "$1") || exit

git reset --quiet --hard "$1" || exit

trap cleanup 0

# Grrr.  Even with --quiet, git merge is spewing messages
git merge --quiet --squash "$current" > /dev/null || exit
SKIP_COMMIT_CHECKS=silent git commit --quiet --amend -m "$msg" ${edit_msg+-e} || exit

trap : 0
