#!/bin/sh

# Given a branch as $1, print the full path of the work-tree
# that houses it.  If no argument given, repot path of the
# main repo.

git rev-parse HEAD > /dev/null || exit
if test $# -ne 1; then
	git rev-parse --path-format=absolute --git-common-dir |
	sed -e 's/.git$//'
	exit
fi
git show-ref --quiet --verify -- "refs/heads/$1" || {
	echo 'First argument must be a valid branch' >&2
	exit 1
}

git worktree list --porcelain | {
dir=$(awk '{gsub("refs/heads/", "")}
	NR == 1 {dir=$2}
	$6 == branch {dir=$2; exit}
	END {print dir}
	' branch="$1" RS=)

if test -z "$dir"; then
	echo "Cannot find worktree for branch $1" >&2
	exit 1
fi

printf '%s' "$dir"
}
