#!/bin/sh

depth=
url=$1
shift

if test "$url" -gt 0 2> /dev/null; then
	depth=$url
	url=$1
	shift
fi

case $url in
http*)
	# By default, remap name to use ssh
	if test -z "$HTTP_OK"; then
		echo 'Remapping http target to git@ to use ssh.  To force http, set HTTP_OK' >&2
		url=$(printf '%s\n' "$url" | sed -e 's|.*://|git@|' -e 's@/@:@')
		shift
	fi
;;
esac


# Parse the url to specify a name for origin
case $url in
*github*) origin=github;;
esac

set -- clone ${depth:+--depth $depth --no-single-branch} ${origin:+--origin="$origin"} "$url" "$@";

# On a bad network, fetching with depth 1 first and then recursively deepening
# prevents starting over from scratch on a network failure.
git_repeat_deepen() {
	local output repo_dir

	printf '%s\n' "git clone --depth 1 $*" >&2
	output=$(git clone --depth 1 "$@" 2>&1) || return 1
	printf '%s\n' "$output"
	repo_dir=$(echo "$output" | awk -F "'" '{print $2}')
	echo "Cloned to depth 1 in $repo_dir.  Attempting to unshallow...."
	set -x

	until git -C "$repo_dir" fetch --unshallow; do
		echo "Network interrupted or repo not yet full.  Deepen by 50..." >&2
		git -C "$repo_dir" fetch --deepen=50
		sleep 2
	done
	set +x
}

if test -z "$depth"; then
	test "$1" = clone || { echo "Unexpected argument: $1" >&2; exit 1; }
	shift
	git_repeat_deepen "$@" || exit
else
	printf 'git %s\n' "$*" >&2
	git "$@" || exit
fi
