#!/bin/sh

# Archive branches by creating a ref in refs/archive
# and deleting the branch.  If no arguments are given,
# archive the current branch after detaching

if test $# = 0; then
	branch=$(git rev-parse --abbrev-ref HEAD)
	set -- "$branch"
	echo "Detaching and archiving the current branch: $branch"
	git checkout --detach
fi

for branch; do
	git update-ref refs/archive/"${branch}" "${branch}" '' \
	&& git branch -D "${branch}"
done

