#!/bin/sh

git rev-parse || exit

# Write the name of the base branch to stdout
if ! ( \
	git config diff.base-branch \
	|| for b in main master "$(git config init.defaultBranch)"
		do
			git rev-parse --abbrev-ref --verify -q "$b" && exit
		done
)
then
	echo >&2 diff.base-branch unset and no main/master ref
	exit 1
fi
