#!/bin/sh

git rev-parse || exit

# Write the name of the base branch to stdout
if ! git config diff.base-branch | grep .; then
	if git show-ref -q refs/heads/main; then
		echo main
	elif git show-ref -q refs/heads/master; then
		echo master
	else
		echo >&2 diff.base-branch unset and no main/master ref
		exit 1
	fi
fi
