#!/bin/sh

# Select the desired vim setting, based on various metadata from git, etc.
# This is expected to be invoked from .vimrc, with the desired setting
# as first argument and path as second.

die() { printf "%s${1:+\n}" "$*"; exit 1; } >&2
git() {
    command git -C "${dirname:?}" "$@"
}
get_remote_url() {
	remote=$(git config branch.${current_branch?}.remote)
	git config remote.$remote.url
}
expandtab() {
	if git config branch.${current_branch?}.expandtab | grep .; then
		return 0
	fi

	case $basename in
	*.go            ) echo no; return;;
	*.yaml          ) echo yes; return;;
	esac

	case $(get_remote_url) in
	*github*        ) echo no;;
	*               ) echo yes;;
	esac
}
get_tabstop() {
	git config branch.${current_branch?}.tabstop | grep . && return

	case $basename in
	*.go            ) echo 8; return;;
	*.yaml          ) echo 4; return;;
	esac

	case $(get_remote_url) in
	*github*        ) echo 8; return;;
	esac
	echo ${TAB_SIZE-8}
}
main(){
	dirname=$(dirname "$2")
	basename=$(basename "$2")
	current_branch=$(git branch --show-current)
	case $1 in
	et|expandtab) expandtab "$@";;
	ts|tabstop) get_tabstop "$@";;
	sw|shiftwidth) get_tabstop "$@";;
	*) die "Unknown setting: $1";;
	esac
}

main "$@"
