#!/bin/sh

# Select the desired vim setting, based on various metadata from git, etc.
# This is expected to be invoked from .vimrc, with the desired setting
# as first argument and path as second.

die() { printf "%s${1:+\n}" "$*"; exit 1; } >&2
git() {
    command git -C "${dirname:?}" "$@"
}
get_remote_url() {
	remote=$(git config branch.${current_branch?}.remote)
	git config remote.$remote.url
}
get_values() {
	tabstop=$(git config branch.${current_branch?}.tabstop)
	expandtab=$(git config branch.${current_branch?}.expandtab)

	case $basename in
	*.go            ) : ${tabstop:=8} ${expandtab:=no};;
	*.yaml          ) : ${tabstop:=4} ${expandtab:=yes};;
	esac

	case $(get_remote_url) in
	*github*        ) : ${tabstop:=8} ${expandtab:=no};;
	*               ) : ${expandtab:=yes}
	esac
	: ${tabstop:=${TAB_SIZE-8}}
	: ${expandtab:=no}
}
main(){
	dirname=$(dirname "$2")
	basename=$(basename "$2")
	current_branch=$(git branch --show-current)
	get_values
	case $1 in
	et|expandtab) echo "${expandtab:?}";;
	ts|tabstop) echo "${tabstop:?}";;
	sw|shiftwidth) echo "${tabstop:?}";;
	*) die "Unknown setting: $1";;
	esac
}

main "$@"
