#!/bin/sh

# Encrypt the contents of the paste buffer into a file
# in ~/.config/secrets

name="$HOME/.config/secrets/${1?}.gpg"
if test -f "$name"; then
	printf "$name already exists!  Delete? (y/N): "
	read yn < /dev/tty
	case $yn in
	y|Y|yes) rm $name;;
	*) echo 'Aborting'; exit 1;;
	esac
fi


if test -t 0; then pbpaste; else cat; fi | gpg -e -r "$EMAIL" > "$name"

if test -s "$name"; then
	gpg -d "$name" 2> /dev/null | wc -lc | {
		read lines chars
		printf "Verified $chars characters encrypted to $name.\n"
		if test "$lines" -gt 0; then
			echo "WARNING: Embedded newlines in $name" >&2
		fi
	}
else
	echo "No data written to $name!!" >&2
	exit 1
fi
