#!/bin/sh

# Encrypt the contents of the paste buffer into a file
# in ~/.config/$USER/secrets

name="$HOME/.config/$USER/secrets/${1?}.gpg"
test -f "$name" && { echo "$name already exists!  Aborting" >&2; exit 1; }

if test -t 0; then pbpaste; else cat; fi | gpg -e -r "$EMAIL" > "$name"

if test -s "$name"; then
	gpg -d "$name" 2> /dev/null | wc -lc | {
		read lines chars
		printf "Successfully wrote and decrypted $chars characters\n"
		if test "$lines" -gt 0; then
			echo "WARNING: Embedded newlines in $name" >&2

		fi
	}
else
	echo "No data written to $name!!" >&2
	exit 1
fi
