#!/bin/sh

# Ack.  The technical debt builds so fast.  Wedging in cruft
# for dvtm now.

# The expectation is that we're running in TMUX or dvtm.  For the moment,
# we can use terminal escape sequences from docker images I often
# run.  Cannot use escape sequences from Apple terminal directly,
# but I don't really care about that.  Abort early and call it a success
# if we aren't in one of the expected environments.
if test -z "$TMUX$DOCKER$DVTM"; then
	exit 0
fi

test -z "$*" && {
	if git_dir=$(git rev-parse --absolute-git-dir 2> /dev/null); then
		set "$(basename $(dirname "$git_dir"))"
	else
		set "$(pwd | sed -e 's@.*/@@' 2> /dev/null)"
	fi
}

if test -z "$left_justify"; then
	patt='.*\(.\{19\}\)'
	repl='<\1'
else
	patt='\(.\{19\}\).*'
	repl='\1>'
fi

title="${DOCKER+$DOCKER:}$( echo "$*" | sed '/.\{20\}/s/^'$patt'$/'$repl/)"

# This is now a poorly named script.  Instead of renaming the window,
# we will change the title of the currnet pane, and rely on the
# tmux configuration to set the string shown in the status bar via
# the automatic-rename-format
if test -n "$DVTM"; then
	printf '\033]0;%s\007' "$title"
elif test -n "$TMUX"; then
	if test -n "$FORCE"; then
		echo 'WARNING: window renamed.  Auto-rename is now disabled' >&2
		tmux rename-window -- "$title"
	else
		tmux select-pane -T "$title"
	fi
else
	printf '\033k%s\033\' "$title"
fi
