#!/bin/sh


test -z "$*" && {
	if git_dir=$(git rev-parse --absolute-git-dir 2> /dev/null); then
		set "$(basename $(dirname "$git_dir"))"
	else
		set "$(pwd 2> /dev/null)"
	fi
}

if test -z "$left_justify"; then
	patt='.*\(.\{19\}\)'
	repl='<\1'
else
	patt='\(.\{19\}\).*'
	repl='\1>'
fi

title="${DOCKER+$DOCKER:}$( echo "$*" | sed '/.\{20\}/s/^'$patt'$/'$repl/)"

if test -n "$TMUX"; then
	tmux rename-window -- "$title"
else
	printf '\033k%s\033\' "$title"
fi
