#!/bin/sh


if test "$1" = .; then
	target=$TMUX_PANE
	adjust=2
else
	target="${1-0.0}"
	adjust=0
fi

if test "$2" -ne 0; then
	end=$(( $(tmux display-message -pt "$target" -F '#{pane_height}') - $adjust))
	start=$(( end - $2 ))
else
	start=-
	end=-
fi

tmux capture-pane -p -E "$end" -S "$start" -t "$target"
