#!/bin/sh

# Given a numeric arugment, find the line on the current
# pane that matches it and store it i a new buffer
die() { printf "%s: %s\n" "$(basename $0)" "$*" >&2; exit 1; }
test "${1-1}" -gt 0 2> /dev/null || die Expected numeric argument

tmux capture-pane -p \
| sed -E -n -e "/^[[:space:]]*$1[[:space:]]+/s///p" \
| tmux loadb
