#!/bin/bash

# Display git branches and prompt for one to checkout.

# TODO: fix the work flow.  When given a non-integer first argument,
# this should filter the branches that match it as a regex

: ${COLUMNS:=$( tput cols 2> /dev/null )}
width=$(git for-each-ref --format='%(refname:short)' refs/heads \
| awk 'length > max {max = length} END {print max + 2}')
format="%(align:$width)%(HEAD) %(refname:short)%(end) %(contents:subject)"
list=$(git branch --color --format="$format")
choice=${1}
count=$(echo "$list" | wc -l | tr -d '[:space:]')

if test "$count" = 1; then
	printf 'Already on only branch: '
	git rev-parse --abbrev-ref HEAD
	exit 0
fi

if ! test "$choice" -gt 0 2> /dev/null; then
	git branch --color=always --format="$format" \
		| nl -ba -s ' ' \
		| perl -nE "chop; say substr(\$_,0,${cols:-${COLUMNS-80}})"
	printf "Select branch: " 
	read -r choice || echo
fi

branch=$( echo "$list" | cut -b 3- | awk '{print $1}' |
	if { test "$choice" -le "$count" && test "$choice" -gt 0; } 2> /dev/null; then
		awk 'NR == c{print $1}' c="$choice"
	elif test -n "$choice"; then
		awk 'match($0,c) {print $1; exit}' c="$choice"
	fi
)

test -n "$branch" && git checkout "$branch"
