#!/bin/bash

# Display git branches and prompt for one to checkout.  Honor
# environment variable TIMEOUT

format='%(align:14)%(HEAD) %(refname:short)%(end) %(contents:subject)'
: ${COLUMNS:=$( tput cols 2> /dev/null )}

list=$(git branch --color --format="$format")
choice=${1}
count=$(echo "$list" | wc -l | tr -d '[:space:]')

test "$count" = 1 && exit

if ! test "$choice" -gt 0 2> /dev/null; then
	git branch --color=always --format="$format" \
		| nl \
		| perl -nE "chop; say substr(\$_,0,${cols:-${COLUMNS-80}} - 1)"
	printf "Select branch: " 
	read -r choice || echo
fi

if { test "$choice" -le "$count" && test "$choice" -gt 0; } 2> /dev/null; then
	branch=$(echo "$list" | cut -b 3- | awk "NR == $choice{print \$1}")
	git checkout "$branch"
elif test -n "$choice"; then
	printf '%s' "$choice" | tmux loadb -
	# Let interactive prompt print
	{ sleep .2; tmux paste-buffer; } &
fi
