#!/bin/sh

# whitespace = indent-with-non-tab
# whitespace = tab-in-indent

v=$(git config core.whitespace)
case $(git config core.whitespace) in
indent-with-non-tab) git config core.whitespace tab-in-indent;;
trailing-space) git config core.whitespace indent-with-non-tab;;
*) git config core.whitespace trailing-space;;
esac

printf 'New value of core.whitespace is: '
git config core.whitespace
