#!/bin/sh

# whitespace = indent-with-non-tab
# whitespace = tab-in-indent

case $(git config core.whitespace) in
indent-with-non-tab) git config core.whitespace tab-in-indent;;
tab-in-indent) git config core.whitespace indent-with-non-tab;;
*) echo 'core.whitespace is not set.  Aborting' >&2; exit 1;;
esac

printf 'New value of core.whitespace is: '
git config core.whitespace
