#!/bin/sh
# Show a count of git trailers used in the history
#
# usage: $0 [-h|--help] [key ...]
#   If no keys are given, output the count of each key.  If keys
#   are given, show the counts for the values of each specified key.
#
# The history can be limited by specifying 'range' in the environment.

if printf '%s\n' "$*" | grep -wqE -- '-h|--help'; then
	sed -nE '2,/^$/{s/# ?//; s|\$0|'"$(basename $0)|"'; p;}' "$0"
	exit
fi
: ${range:=HEAD}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

git log "$range" --format='%(trailers:unfold)' | sed -e '/^$/d' > "$tmp"

if test ! -s "$tmp"; then
	echo "No trailers found."
	exit 0
fi

if test $# = 0; then
	awk -F': ' '{ a[$1] += 1 }
		END { for(k in a) print a[k], k }
	' OFS=\\t "$tmp" | sort -rn
else
	for key; do
		echo "*** $key ****"
		awk -F': ' '$1 == k{ a[substr($0, length($1) + 3)] += 1 }
			END { for(v in a) print a[v], v }
		' k="$key" OFS=\\t "$tmp" | sort -rn
	done
fi
