#!/bin/sh

output_dir=${TMPDIR-/tmp}
output_path=${output_dir%/}/ttwrap.$$
fifo=${output_dir}/ttwrap.fifo

trap 'rm -f $fifo' 0
mkfifo $fifo || exit

tput smcup || exit

tee "$output_path" < $fifo &

exec 3>&1
exec > $fifo

"$@"
status=$?

case $status in
0) status_txt=SUCCESS;;
*) status_txt=FAILURE;;
esac

exec >&3

printf "*********** $status_txt *****************\n"
printf 'press <enter> to exit alternate screen buffer\n'
printf 'Output has been saved to %s\n' "$output_path"

read
tput rmcup
printf 'Output has been saved to %s\n' "$output_path"
exit $status
