#!/bin/sh

main() {
	check_subject "$@" || return 1
}

check_subject() {
	# Abort if the first line of the message is non-conforming
	< "$1" awk '
		NR == 1 && ! /[a-z)}/"A-Z0-9]$/ {
			print "Summary of commit message must end with one of a-zA-Z)}/\"0-9" > "/dev/stderr"
			exit 1;
		}
		NR == 1 && length > maxlen {
			err = "Summary of commit message is too long"
			err = err " (%d > MAX_GIT_SUMMARY)\n"
			printf err, length > "/dev/stderr"
			exit 1;
		}
	' maxlen=${MAX_GIT_SUMMARY-60}
}


if ! main "$@"; then
	echo "commit-msg hook is rejecting this commit" >&2
	exit 1
fi
