#!/bin/sh

. "$(dirname $0)"/common-hook-functions

main() {
	msg=$(check_subject "$@") || die "$msg"
	run_local_hooks
}


check_subject() {
	bad_end='.!?'  # Characters not allowed as final char of subject

	# Abort if the first line of the message is non-conforming
	< "$1" awk '
		match($0, end) {
			printf "Summary should not end with punctuation"
			exit 1
		}
		length > maxlen {
			printf "Summary is %d chars too long" \
				" (MAX_GIT_SUMMARY == %d)", length - maxlen, maxlen
			exit 1;
		}
		{ exit 0 }
	' maxlen=${MAX_GIT_SUMMARY-50} end="[${bad_end}]$"
}


main "$@"
