#!/bin/sh

remote=$( git rev-parse --symbolic-full-name --abbrev-ref @{u} | cut -d / -f 1 )
url=$( git ls-remote --get-url "$remote" )
case $url in
*github*) git config user.email "${GITHUB_EMAIL?}" ;;
*)        git config user.email "${EMAIL?}" ;;
esac
git config user.name "${NAME?}"
echo  "email set to $(git config user.email)" >&2
