#!/bin/sh

valid_chars=':a-zA-Z0-9_./-'  # Characters that are acceptable in path names
against=$(git rev-parse --verify HEAD 2>/dev/null || git hash-object -t tree /dev/null)

die() {
	printf 'Pre-commit hook is rejecting this commit: '
	printf '%s\n' "$1";
	printf 'Use --no-verify (-n) to ignore\n'
	exit 1
} >&2

# Reject names with non standard characters
if invalid=$(git diff --cached --name-only --diff-filter=A -z $against |
	LC_ALL=C tr -d "\000${valid_chars}" | xxd | cut -d: -f 2- | tr -s ' ' | grep .)
then
	die "Invalid characters in filename: $invalid"
fi

if ! git diff-index --check --cached $against --; then
	die 'Whitespace errors'
fi
