#!/bin/sh

get_ticket() {
	branch=$(command git rev-parse --abbrev-ref HEAD)
	ticket=$(
		# get-ticket-from-branch is expected to be a local
		# script that may not exist
		command git config branch."$branch".ticket ||
		get-ticket-from-branch "$branch" 2> /dev/null
	)
	if test -z "$ticket" && test -z "$ALLOW_NO_TICKET" &&
		! test "$(command git config core.require-trailers)" = false
	then
		echo "No ticket configured for branch $branch" >&2
		return 1
	fi
}

get_ticket || exit 1
if test -n "$ticket"; then
	echo adding ticket
	git-interpret-trailers --in-place --if-exists doNothing --trailer ticket="$ticket" "$1"
fi
